CREATE SEQUENCE STORY_CONTRIBUTIONS_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE STORY_CONTRIBUTIONS
(
    RECORD_ID         BIGSERIAL PRIMARY KEY,
    CONTRIBUTION_ID   VARCHAR(20) NOT NULL,
    STORY_ID          VARCHAR(20) NOT NULL,
    AUTHOR_ID         VARCHAR(20) NOT NULL,
    CONTRIBUTOR_ID    VARCHAR(20) NOT NULL,
    PARENT_ENTRY_ID   BIGINT NOT NULL,
    CONTENT           TEXT NOT NULL,
    STATUS            VARCHAR(20) NOT NULL,
    CRUD_VALUE        VARCHAR(20) NOT NULL,
    LOCAL_TS          TIMESTAMP NOT NULL,
    HOST_TS           TIMESTAMP NOT NULL,
    UUID              UUID NOT NULL
);

CREATE UNIQUE INDEX IDX_STC_01 ON STORY_CONTRIBUTIONS(CONTRIBUTION_ID);

CREATE INDEX IDX_STC_02 ON STORY_CONTRIBUTIONS(STORY_ID);

CREATE INDEX IDX_STC_03 ON STORY_CONTRIBUTIONS(AUTHOR_ID);

CREATE INDEX IDX_STC_04 ON STORY_CONTRIBUTIONS(CONTRIBUTOR_ID);

CREATE INDEX IDX_STC_05 ON STORY_CONTRIBUTIONS(STATUS);