CREATE SEQUENCE NOTIFICATION_SUBSCRIPTIONS_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE NOTIFICATION_SUBSCRIPTIONS(
    RECORD_ID          BIGSERIAL PRIMARY KEY,
    SUBSCRIPTION_ID    VARCHAR(20) NOT NULL,
    USER_ID            VARCHAR(20),
    EMAIL              VARCHAR(255) NOT NULL,
    STATUS             VARCHAR(20) NOT NULL,
    CRUD_VALUE         VARCHAR(20) NOT NULL,
    LOCAL_TS           TIMESTAMP NOT NULL,
    HOST_TS            TIMESTAMP NOT NULL,
    UUID               UUID NOT NULL
);

CREATE UNIQUE INDEX IDX_NS_01 ON NOTIFICATION_SUBSCRIPTIONS(SUBSCRIPTION_ID);
CREATE UNIQUE INDEX IDX_NS_02 ON NOTIFICATION_SUBSCRIPTIONS(EMAIL);
CREATE INDEX IDX_NS_03 ON NOTIFICATION_SUBSCRIPTIONS(STATUS);