spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: false

  main:
    lazy-initialization: true

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              redirect-uri: https://unsent-api-1-0-0-snapshot.onrender.com/login/oauth2/code/google

server:
  port: ${PORT:8080}